openapi: "3.0.0"
info:
  title: Tass API
  description: API description in Markdown.
  version: 1.0.0

tags:
  - name: User
    description: Пользователи
  - name: Presets
    description: Пресеты

paths:

  #-------------------------
  # Presets
  #-------------------------
  /user/columns:
    get:
      tags:
        - Presets
      summary: Получение списка названий колонок
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/UserTypeParams'
      responses:
        200:
          $ref: 'definitions.yaml#/components/responses/Presets'

  /user/:userId/presets:
    get:
      tags:
        - Presets
      summary: Получение cписка пресетов
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/UserIdParams'
      responses:
        200:
          $ref: '#/components/responses/UserPresets'

  /user/:userId/preset:
    post:
      tags:
        - Presets
      summary: Создание пресета
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/PresetIdParams'
        - $ref: '#/components/parameters/UserIdParams'
      requestBody:
        $ref: '#/components/requestBodies/UserPreset'
      responses:
        200:
          $ref: '#/components/responses/UserPreset'

  /user/:userId/preset/:presetId:
    get:
      tags:
        - Presets
      summary: Получение текущего пресета
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/PresetIdParams'
        - $ref: '#/components/parameters/UserIdParams'
      responses:
        200:
          $ref: '#/components/responses/UserPreset'
    put:
      tags:
        - Presets
      summary: Обновление пресета
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/PresetIdParams'
        - $ref: '#/components/parameters/UserIdParams'
      requestBody:
        $ref: '#/components/requestBodies/UserPreset'
      responses:
        200:
          $ref: '#/components/responses/UserPreset'
    delete:
      tags:
        - Presets
      summary: Удаление пресета
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/PresetIdParams'
        - $ref: '#/components/parameters/UserIdParams'
      responses:
        200:
          description: OK

  #-------------------------
  # User
  #-------------------------
  /users/:type:
    get:
      tags:
        - User
      summary: Получение списка пользователей
      security:
        - AuthToken: []
      parameters:
        - $ref: '#/components/parameters/UserTypeParams'
        - $ref: 'definitions.yaml#/components/parameters/filterParams'
        - $ref: 'definitions.yaml#/components/parameters/orderParam'
        - $ref: 'definitions.yaml#/components/parameters/orderByParam'
      responses:
        200:
          $ref: 'definitions.yaml#/components/responses/ListData'


#-------------- Definitions ---------------

components:

  parameters:
    UserTypeParams:
      name: type
      in: path
      required: true
      description: Тип пользователя
      schema:
        type: string
        enum: [customer, user]
        default: customer
    PresetIdParams:
      name: presetID
      in: path
      required: true
      description: ID пресета
      schema:
        type: number
    UserIdParams:
      name: userID
      in: path
      required: true
      description: ID пользователя
      schema:
        type: number

  schemas:
    Presets:
      type: object
      properties:
        title:
          type: string
        presets:
          type: array
          items:
            $ref: 'definitions.yaml#/components/schemas/Item'

  requestBodies:
    UserPreset:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Presets'

  responses:
    UserPreset:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Presets'

    UserPresets:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: 'definitions.yaml#/components/schemas/Item'
